### ISSUE TITLE
[Discussion] Implementing ToBeAFolderWithFiles

### ISSUE THREAD

**Issue by izacsc** [nginformatica/advpl-testsuite#10]
Hello!

I was implementing ```ToBeAFolderWithFiles``` and I wasn't able to compile it:
```Method ToBeAFolderWithFiles is redefined on class FLUENTEXPR```

So... Should we change the method name? Or use another aproach?

I thought something like:
```
::Expect( '\problems' ):ToBe():AFolder():WithFiles({'worldpeace.txt', 'poverty.txt'})

```
But this would require some refactoring to make the other methods consistents ( ```TobeAFile()``` - > ```ToBe():AFile()```) and to rethink the way messages are shown ( ToBe():AFolder():WithFiles should emit only one message).

On the other hand this would reduce the code duplication ( File, FileWithContents, Folder, FolderWithFiles, etc...)

What do you think about it?

**Comment by haskellcamargo** [comment]
This happens because `ToBeAFolder` has length 11. AdvPL limits the function names to 10 and `ToBeAFolderWithFiles` is taken as the same.

**but...**

There is a trick! There is an internal class in AdvPL called `LongNameClass`, that allows method names to be bigger (I believe about 256 chars). So, we can make it work [changing this line](https://github.com/nginformatica/advpl-testsuite/blob/master/src/fluentexpr.prw#L36):

```diff
-Class FluentExpr
+Class FluentExpr From LongNameClass
```

**Comment by izacsc** [comment]
Like a charm! 
I actually tried this before but instead of ```LongNameClass``` I wrote ```LongClassName``` 😢
